engine = "Microsoft SQL Server"
server = None
database = None
username = None
password = None
authType = None
connString = None
connTest = None
databaseEdits = {}
objListTab = None
sett = None
compareObj = None
masterPassword = "P@ssw0rd"
openedCommitTab = []
openedCommitTabText = []
version = "alpha 1.2"
darkmode = False
connectionMode = 'connectserver'
serverTypeMerge = None
serverMerge = None
usernameMerge = None
passwordMerge = None
authTypeMerge = None

#ENGINE MSSSQL
DBTEST = "master"
DBGIT = "SQLVC"
SQLSERVER = "ODBC Driver 13 for SQL Server"
WORKSPACE_SELECTED = []
